# Generated by Django 3.2.6 on 2021-08-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_auto_20210829_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto', verbose_name='Producto')),
                ('fk_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.venta', verbose_name='Venta')),
            ],
        ),
    ]
