# Generated by Django 3.2.6 on 2021-08-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, upload_to='static/img/productos/'),
        ),
    ]
