# Generated by Django 3.2.6 on 2021-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_alter_producto_foto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='n_venta',
            field=models.IntegerField(unique=True),
        ),
    ]
