# Generated by Django 3.2.6 on 2021-09-09 14:18

import Inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_producto_foto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, upload_to=Inventario.models.url_producto),
        ),
    ]
