# Generated by Django 3.2.6 on 2021-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_alter_cliente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='n_compra',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='n_venta',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
